// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1bcPH33-kTlEXJScbMiYjSkUIrXd9-ok',
    appId: '1:611669901957:web:92aca357947c865cfe5fec',
    messagingSenderId: '611669901957',
    projectId: 'master-helper-b73a7',
    authDomain: 'master-helper-b73a7.firebaseapp.com',
    databaseURL: 'https://master-helper-b73a7.firebaseio.com',
    storageBucket: 'master-helper-b73a7.appspot.com',
    measurementId: 'G-Y9T8P59H6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ78sMO1he6Hn_lt0T4wEkmnfwZQs1YMs',
    appId: '1:611669901957:android:09da4731d90ca50cfe5fec',
    messagingSenderId: '611669901957',
    projectId: 'master-helper-b73a7',
    databaseURL: 'https://master-helper-b73a7.firebaseio.com',
    storageBucket: 'master-helper-b73a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKT7777880A-Ie5qe6PonDSMqCqAmH2ss',
    appId: '1:611669901957:ios:a436603a43a25cfefe5fec',
    messagingSenderId: '611669901957',
    projectId: 'master-helper-b73a7',
    databaseURL: 'https://master-helper-b73a7.firebaseio.com',
    storageBucket: 'master-helper-b73a7.appspot.com',
    androidClientId: '611669901957-3810m4dli2h0miof80n6c7r5gcfm0b75.apps.googleusercontent.com',
    iosClientId: '611669901957-b0s9rhpp5vch0un2tsr3b0qa1dgv0cnu.apps.googleusercontent.com',
    iosBundleId: 'com.masters.farmiaPrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKT7777880A-Ie5qe6PonDSMqCqAmH2ss',
    appId: '1:611669901957:ios:a436603a43a25cfefe5fec',
    messagingSenderId: '611669901957',
    projectId: 'master-helper-b73a7',
    databaseURL: 'https://master-helper-b73a7.firebaseio.com',
    storageBucket: 'master-helper-b73a7.appspot.com',
    androidClientId: '611669901957-3810m4dli2h0miof80n6c7r5gcfm0b75.apps.googleusercontent.com',
    iosClientId: '611669901957-b0s9rhpp5vch0un2tsr3b0qa1dgv0cnu.apps.googleusercontent.com',
    iosBundleId: 'com.masters.farmiaPrototype',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1bcPH33-kTlEXJScbMiYjSkUIrXd9-ok',
    appId: '1:611669901957:web:02ff45b6004b41e6fe5fec',
    messagingSenderId: '611669901957',
    projectId: 'master-helper-b73a7',
    authDomain: 'master-helper-b73a7.firebaseapp.com',
    databaseURL: 'https://master-helper-b73a7.firebaseio.com',
    storageBucket: 'master-helper-b73a7.appspot.com',
    measurementId: 'G-MR8ZPH4R8R',
  );
}
